apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels: 
    name: voting-app-pod
    app: demo-voting-app
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
